---
AWSTemplateFormatVersion: '2010-09-09'
Description: MU IAM roles and keys for pipeline
Resources:
  CodeBuildCDAcptRole:
    Type: AWS::IAM::Role
    Properties:
      Policies:
      - PolicyName: deploy-acpt-env-1
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
        - Effect: Allow
          Principal:
            AWS: "*"
          Action:
          - sts:AssumeRole