---
AWSTemplateFormatVersion: '2010-09-09'
Description: MU IAM roles and keys for pipeline
Resources:
  SampleManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowAllUsersToListAccounts
            Effect: Allow
            Action:
              - iam:*
            Resource: *

  CodeBuildCIRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub mu-pipeline-my-app-ci-us-east-1
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - codebuild.amazonaws.com
            - iam.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - !Ref SampleManagedPolicy
