---
AWSTemplateFormatVersion: '2010-09-09'
Description: MU IAM roles and keys for pipeline
Resources:
  CodeBuildCDAcptRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub mu-pipeline-my-app-mu-acpt-us-east-1
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            AWS: "*"
          Action:
          - sts:AssumeRole
      Path: "/"