---
AWSTemplateFormatVersion: '2010-09-09'
Description: MU IAM roles and keys for pipeline
Resources:
  CodeBuildCDAcptRole:
    Type: AWS::IAM::Role
    Condition: IsAcptEnabled
    Properties:
      RoleName: !Sub mu-pipeline-my-app-cd-acpt-us-east-1
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - iam.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"