---
AWSTemplateFormatVersion: '2010-09-09'
Description: MU IAM roles and keys for pipeline
Resources:
  CodeBuildCDAcptRole:
    Type: AWS::IAM::Role
    Properties:
      Policies:
      - PolicyName: assume-mu-acpt-pipeline
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
            - sts:AssumeRole
            Resource:
            - !Sub arn:aws:iam::002838516900:*/mu-pipeline-my-app-mu-acpt-us-east-1
            Effect: Allow