---
AWSTemplateFormatVersion: '2010-09-09'
Description: MU IAM roles and keys for pipeline
Resources:
  CodeBuildCIRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${Namespace}-pipeline-${ServiceName}-ci-${AWS::Region}
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - codebuild.amazonaws.com
            - iam.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
       - PolicyName: iam-role
         PolicyDocument:
           Version: '2012-10-17'
           Statement:
           - Action:
             - iam:*
             Resource: 'arn:aws:iam::*:role/aws-service-role/iam.amazonaws.com/IAMFullAccess*'
             Condition:
               StringLike:
                 iam:AWSServiceName: iam.amazonaws.com
             Effect: Allow